import NavigationBar from "./components/NavigationBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="relative h-48" lang="en">
      <body>
        <NavigationBar />
        <main className="mb-40 body">{children}</main>
      </body>
    </html>
  );
}
